version: '3.1'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ${DATABASE}       # Имя базы данных
      MONGO_INITDB_ROOT_USERNAME: ${USER}       # Имя пользователя
      MONGO_INITDB_ROOT_PASSWORD: ${PASSWORD}   # Пароль
    volumes:
      - mongo_data:/data/db
    networks:
      - web_network  # Создаем внешнюю сеть

  backend: # Название вашего сервиса
    build: ./backend
    container_name: python_api
    restart: always
    networks:
      - web_network  # Оставляем только внутреннюю сеть
      -
volumes:
  mongo_data: