services:
  mongodb:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: CashAndGo
      MONGO_INITDB_ROOT_PASSWORD: 2093100Tbm
      MONGO_INITDB_DATABASE: CashAndGoDB
    volumes:
      - mongo_data:/data/db
    networks:
      - web_network  

  backend: 
    build: .
    container_name: python_api
    restart: always
    ports:
      - "5000:5000"
    networks:
      - web_network  
    volumes:
      - ./data:/api/data
    environment:
      ADMIN_LOGIN: "6e6r4"
      ADMIN_PASSWORD: "!Be6r0Nyh0v2281488!$$o$$pi$$o$$ZlpT0kEH!!AAA"
      JWT_ACCESS_KEY: "fa39f70f820bc7bcf60ef314f134c6cfb29ad6b7d44f7beac31d9dda261b1828"
      JWT_REFRESH_KEY: "fd18f4116af594962aecd6d0524d1de5eff0df09ebc2959411e82b582fc3b04ba4286edbbf49999859b3eb80cbcead34f8738efc22dff886d6259cd16f3f85b9"
      JWT_ALGORITHM: "HS256"
      ACCESS_TOKEN_EXPIRE_MINUTES: 15
      REFRESH_TOKEN_EXPIRE_DAYS: 30

networks:
  web_network:
    driver: bridge

volumes:
  mongo_data: