services:
  mongodb:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: CashAndGo
      MONGO_INITDB_ROOT_PASSWORD: 2093100Tbm
      MONGO_INITDB_DATABASE: CashAndGoDB
    volumes:
      - mongo_data:/data/db
    networks:
      - web_network  

  backend: 
    build: .
    container_name: python_api
    restart: always
    ports:
      - "5000:5000"
    networks:
      - web_network  
    volumes:
      - ./data:/api/data
    environment:
      ADMIN_LOGIN: "6e6r4"
      ADMIN_PASSWORD: "!Be6r0Nyh0v2281488!$$o$$pi$$o$$ZlpT0kEH!!AAA"
      JWT_ACCESS_KEY: "fa39f70f820bc7bcf60ef314f134c6cfb29ad6b7d44f7beac31d9dda261b1828"
      JWT_REFRESH_KEY: "fd18f4116af594962aecd6d0524d1de5eff0df09ebc2959411e82b582fc3b04ba4286edbbf49999859b3eb80cbcead34f8738efc22dff886d6259cd16f3f85b9"
      JWT_ALGORITHM: "HS256"
      ACCESS_TOKEN_EXPIRE_MINUTES: 15
      REFRESH_TOKEN_EXPIRE_DAYS: 30
      API_KEY: "e94bd4d653c6149c7af98fe1"
      EXCHANGE_TO_RATE_REQUEST: "https://xecdapi.xe.com/v1/convert_to?from=USD%2CEUR%2CRUB%2CJPY%2CMYR%2CINR%2C%20AED%2CGBP%2CSG D%2CCHF%2CAUD%2CHKD%2CCAD%2CTWD%2CKRW%2CPHP%2CNZD%2CCNY%2CSAR%2CQAR%2CBHD&to=THB&obsolete=false"
      EXCHANGE_FROM_RATE_REQUEST: "https://xecdapi.xe.com/v1/convert_from?from=THB&to=USD%2CEUR%2CRUB%2CJPY%2CMYR%2CINR%2CAED%2CGBP%2CSGD%2CCHF%2CAUD%2CHKD%2CCAD%2CTWD%2CKRW%2CPHP%2CNZD%2CCNY%2CSAR%2CQAR%2CBHD"
      GET_TETHER_TO_RUB_AND_THB: "https://api.coingecko.com/api/v3/simple/price?ids=tether&vs_currencies=thb,rub"
      GET_ALL_THB_RATES: "https://v6.exchangerate-api.com/v6/e94bd4d653c6149c7af98fe1/latest/THB"
      DB_NAME: "CashAndGoDB"
      DB_USERNAME: "CashAndGo"
      DB_USER_PASSWORD: "2093100Tbm"

networks:
  web_network:
    driver: bridge

volumes:
  mongo_data: