services:
  mongodb:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    env_file:
      - data/mongoconnection.env
    volumes:
      - mongo_data:/data/db
    networks:
      - web_network  # Создаем внешнюю сеть

  backend: # Название вашего сервиса
    build: .
    container_name: python_api
    restart: always
    ports:
      - "5000:5000"
    networks:
      - web_network  # Оставляем только внутреннюю сеть

networks:
  web_network:
    driver: bridge

volumes:
  mongo_data: